version: "3"

services:
  srv-app-sessions:
    build: ./srv-app-sessions
    restart: always
    environment:
      - SERVICE_NAME=srv-app-sessions
    container_name: srv-app-sessions
    env_file:
      - ./.env

  auth-simple:
    build:
      context: ./auth-simple
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - PUBLIC_POCKETBASE_URL=${PUBLIC_POCKETBASE_URL}
        - PUBLIC_BACKGROUND_IMAGE=${PUBLIC_BACKGROUND_IMAGE}
        - PUBLIC_TRANSLATIONS_ENABLED=${PUBLIC_TRANSLATIONS_ENABLED}
    restart: always
    environment:
      - NODE_ENV=production
      - SERVICE_NAME=auth-simple
      - OTP_ENABLED=false
      - OTP_APP_NAME=NELREINATECH
      - OTP_SESSION_EXPIRED=3600

    container_name: auth-simple
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth-simple.rule=Host("app.auth-simple.localhost")
    env_file:
      - ./.env

networks:
  default:
    name: traefik
    external: true
